const swaggerAutogen = require('swagger-autogen')();

const doc = {
  info: {
    title: 'HMS API',
    description: 'Healthcare Management System API documentation. All endpoints require authentication unless otherwise stated.',
    version: '1.0.0',
  },
  host: process.env.NODE_ENV === 'production' ? process.env.APP_URL : 'localhost:5008',
  basePath: '/api/v1',
  schemes: ['http', 'https'],
  securityDefinitions: {
    bearerAuth: {
      type: 'apiKey',
      name: 'Authorization',
      in: 'header',
      description: 'Enter your Bearer token in the format `Bearer <token>`',
    },
  },
  security: [
    { bearerAuth: [] }
  ],
};

const outputFile = './swagger-output.json';
const endpointsFiles = [
  '../routes/authRoutes.js',
  '../routes/accessControlRoutes.js',
  '../routes/accounts.routes.js',
  '../routes/admissionRoute.js',
  '../routes/aiRoutes.js',
  '../routes/ANCRoute.js',
  '../routes/attendanceRoutes.js',
  '../routes/bedRoutes.js',
  '../routes/broadCastRoutes.js',
  '../routes/chatRoutes.js',
  '../routes/claimsMedicineRoutes.js',
  '../routes/claimsRoute.js',
  '../routes/clinicalInterventionRoutes.js',
  '../routes/commentsRoutes.js',
  '../routes/consultationRoutes.js',
  '../routes/departmentCallRoutes.js',
  '../routes/departmentRoutes.js',
  '../routes/dischargeRoute.js',
  '../routes/doctorsNoteRoutes.js',
  '../routes/drugHistory.routes.js',
  '../routes/educationMaterialsRoutes.js',
  '../routes/faceRoutes.routes.js',
  '../routes/familyHealthHistory.routes.js',
  '../routes/fluidMonitoring.js',
  '../routes/gdrgRoutes.js',
  '../routes/groupRoutes.js',
  '../routes/icd10Routes.js',
  '../routes/information_manager.route.js',
  '../routes/invoice.routes.js',
  '../routes/institutionRoutes.js',
  '../routes/institutionChatRoutes.js',
  '../routes/labRoutes.js',
  '../routes/laboratoryTestRoutes.js',
  '../routes/labInvestigationRoute.js',
  '../routes/leaveRoutes.routes.js',
  '../routes/meetingRoutes.js',
  '../routes/messageRoute.js',
  '../routes/messageTempRoute.js',
  '../routes/maternityRoutes.js',
  '../routes/notificationRoutes.js',
  '../routes/nhiaVettingRoutes.js',
  '../routes/nurseHandoverRoutes.js',
  '../routes/partographRoute.js',
  '../routes/pastMedicalHistory.routes.js',
  '../routes/patientAllergy.routes.js',
  '../routes/patientAdvancedFeatures.routes.js',
  '../routes/patientBookingRoutes.js',
  '../routes/patientCarePlanRoutes.js',
  '../routes/patientChronicCondition.routes.js',
  '../routes/patientDiagnosisRoutes.js',
  '../routes/patientLabRoutes.js',
  '../routes/patientNoteRoute.js',
  '../routes/patientOccupationHistory.routes.js',
  '../routes/patientRiskAssessment.routes.js',
  '../routes/payment.routes.js',
  '../routes/paymentMethodRoute.js',
  '../routes/permissionRoute.js',
  '../routes/prescriptionRoute.js',
  '../routes/preOpChecklistRoutes.js',
  '../routes/procedureRoutes.js',
  '../routes/recordOfficerRoute.js',
  '../routes/reportRoute.js',
  '../routes/requestRoutes.js',
  '../routes/RerralRoutes.js',
  '../routes/rotationRoutes.js',
  '../routes/scheduleRoutes.js',
  '../routes/serviceRoutes.js',
  '../routes/shdeduleAppointmentRoute.js',
  '../routes/staffDocuments.route.js',
  '../routes/storeRoutes.js',
  '../routes/statisticsRoutes.js',
  '../routes/subscriptionRoutes.js',
  '../routes/surgeryProcedureHistoryRoutes.js',
  '../routes/SummaryControllerRoutes.js',
  '../routes/systemRoutes.js',
  '../routes/theatre/caseCartRoutes.js',
  '../routes/theatre/equipmentRoutes.js',
  '../routes/theatre/theatreBookingRoutes.js',
  '../routes/theatre/operatingRoomRoutes.js',
  '../routes/theatrePatientRoutes.js',
  '../routes/transferRoutes.js',
  '../routes/treatmentPlanRoutes.js',
  '../routes/ultrasoundRoutes.js',
  '../routes/vitalSignsRoutes.js',
  '../routes/wardsRoutes.js',
  '../routes/waitListRoutes.js',
];

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
  console.log('Swagger documentation generated successfully');
});
