const roles = {
    ADMIN: {
        permissions: ['CREATE_DEPARTMENT', 'UPDATE_DEPARTMENT', 'DELETE_DEPARTMENT', 'ASSIGN_ROLES', 'MANAGE_STAFF']
    },
    DOCTOR: {
        permissions: ['VIEW_PATIENT_RECORDS', 'UPDATE_PATIENT_RECORDS', 'ADMIT_PATIENTS', 'DISCHARGE_PATIENTS', 'ORDER_TESTS', 'PRESCRIBE_MEDICATIONS']
    },
    NURSE: {
        permissions: ['VIEW_PATIENT_RECORDS', 'UPDATE_PATIENT_RECORDS', 'ADMIT_PATIENTS', 'DISCHARGE_PATIENTS', 'ORDER_TESTS']
    },
    RECEPTIONIST: {
        permissions: ['SCHEDULE_APPOINTMENTS', 'VIEW_BED_STATUS']
    },
    TECHNICIAN: {
        permissions: ['MANAGE_INVENTORY']
    }
};
