exports.staff_permissions = [
    "CAN HAVE ACCESS TO CONSULTATION",
    "CAN HAVE ACCESS TO RECORDS",
    "CAN HAVE ACCESS TO OPD",
    "CAN HAVE ACCESS TO MATERNITY",
    "CAN HAVE ACCESS TO LAB",
    "CAN HAVE ACCESS TO PHARMACY",
    "CAN HAVE ACCESS TO MALE WARD",
    "CAN HAVE ACCESS TO STORES",
    "administrator"
];
